# Docker Compose for PostgreSQL & Prisma

# version: '3.8'

services:
  postgres:
    image: postgres
    container_name: smart-task-manager-db
    restart: always
    environment:
      POSTGRES_USER: samadmin
      POSTGRES_PASSWORD: sampassword
      POSTGRES_DB: smart_task_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
